---
cache:
  dir: /tmp/trivy-cache

debug: true

ignorefile: .trivyignore.yml

insecure: true

scan:
  disable-telemetry: false
  parallel: 8
  show-suppressed: true
  skip-dirs:
    - .ansible
    - .cache
    - .mypy_cache
    - .pre-commit-trivy-cache
    - .pytest_cache
    - .ruff_cache
    - .terraform
    - .venv
    - common/.ansible
    - common/.terraform
    - deployment/.terraform
    - data
    - logs
    - tmp
  skip-version-check: true

severity:
  - HIGH
  - CRITICAL
