---
name: Continuous Integration

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  workflow_dispatch:

  workflow_run:
    workflows:
      - CI - Pre-Commit
    type:
      - completed

permissions: read-all

jobs:
  ci:
    if: {% raw %}"${{ github.event.workflow_run.conclusion == 'success' }}"{% endraw %}
    runs-on: ubuntu-latest
    name: Run CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
{%- if cookiecutter.project_support_golang %}
  go-build-test:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: ">=1.19.2"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
{%- endif %}
