---
name: Continuous Delivery

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  workflow_dispatch:

  workflow_run:
    workflows:
      - Continuous Integration
    type:
      - completed

permissions: read-all

jobs:
  cd:
    name: Run CD
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
