---
name: Pull Requests

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  workflow_dispatch:

  workflow_run:
    workflows:
      - CI - Pre-Commit
    type:
      - completed

permissions: read-all

jobs:
  trigger:
    if: >-
      ${{ github.event_name == 'pull_request' }} &&
      ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Write Output
        run: echo "### Triggering workflow! :rocket:" >> $GITHUB_STEP_SUMMARY
  automerge:
    name: Merge PR
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs:
      - trigger
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.5.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor,patch
