---
name: Continuous Integration

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  workflow_dispatch:

  # yamllint disable-line rule:empty-values
  pull_request:

  push:
    branches:
      - "*"
    tags-ignore:
      - "**"

permissions: read-all

jobs:
  token:
    name: Generate token
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Output token
        run: echo "token=${{ steps.app-token.outputs.token }}" >> $GITHUB_OUTPUT

  ##############################################################################
  #
  # Run on everything but Releases and WIP
  #
  ##############################################################################
  linting:
    if: >-
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !startsWith(github.event.head_commit.message, 'WIP')
    name: "Run Linting against all files"
    uses: jlec/github-actions/.github/workflows/reusable-linting.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  dependabot:
    name: "Handle dependabot PR"
    if: >-
      ${{ github.actor == 'dependabot[bot]' }} &&
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !startsWith(github.event.head_commit.message, 'WIP')
    needs:
      - linting
    uses: jlec/github-actions/.github/workflows/reusable-pr-dependabot.yml@main
    permissions:
      contents: write
      pull-requests: write
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  ci-generic:
    name: "Run generic CI"
    if: >-
      ${{ github.actor != 'dependabot[bot]' }} &&
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !startsWith(github.event.head_commit.message, 'WIP')
    needs:
      - dependabot
      - linting
    uses: jlec/github-actions/.github/workflows/reusable-ci-generic.yml@main
    permissions:
      contents: write
      pull-requests: write
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  ci-release:
    name: "Run Release CI"
    if: >-
      ${{ github.actor != 'dependabot[bot]' }} &&
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !startsWith(github.event.head_commit.message, 'WIP')
    needs:
      - ci-generic
      - token
    uses: jlec/github-actions/.github/workflows/reusable-ci-release.yml@main
    permissions:
      contents: write
      pull-requests: write
    secrets:
      github-token: ${{ needs.token.outputs.token }}
    with:
      licensed-files: |-
        LICENSE
