---
name: Release Bump

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  filter:
    if: >-
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !startsWith(github.event.head_commit.message, 'WIP')
    runs-on: ubuntu-latest
    steps:
      - name: Release name
        run: echo "${{ github.event.head_commit.message }}"
  pre-commit:
    name: "Run Pre-commit against all files"
    needs: filter
    uses: jlec/github-actions/.github/workflows/reusable-pre-commit.yml@main
  gitleaks:
    name: "Run GitLeaks"
    needs: filter
    uses: jlec/github-actions/.github/workflows/reusable-gitleaks.yml@main
  license-year:
    name: "Fix license year"
    needs:
      - pre-commit
      - gitleaks
    uses: jlec/github-actions/.github/workflows/reusable-license-year.yml@main
    permissions:
      contents: write
      pull-requests: write
  commitizen-bump:
    name: "Bump version and create changelog with commitizen"
    needs: license-year
    uses: jlec/github-actions/.github/workflows/reusable-commitizen-bump.yml@main
    permissions:
      contents: write
