---
name: Release Artefacts

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release-and-clean:
    name: Release the code & clean up
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    env:
      GOPRIVATE: github.com/jlec-go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Cleanup action status
        uses: ouzi-dev/commit-status-updater@v2
        with:
          status: "success"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "GithubActions - ${GITHUB_WORKFLOW}"
          ignoreForks: true
