---
name: GO Build & test

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      pat:
        required: true

jobs:
  go-build-test:
    name: go-build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: "git config --global url.'https://jlec:${{ secrets.pat }}@github.com/'.insteadOf git@github.com:"
      # yamllint disable-line rule:line-length
      - run: "git config --global url.'https://jlec:${{ secrets.pat }}@github.com/'.insteadOf 'https://github.com/'"
      - run: "git config --global url.'https://'.insteadOf git://"
      - run: "git config --global user.name jlec"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: ">=1.21.0"
      - name: GO Build
        run: go build -v ./...
      - name: GO Test
        run: go test -v ./...
      - name: GO vet
        run: go vet ./...
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
          min-go-version: 1.21.0
