---
name: License Year

# yamllint disable-line rule:truthy
on:
# yamllint disable-line rule:empty-values
  workflow_call:

jobs:
  license-year:
    name: license-year
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update License year
        uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assignees: jlec
          labels: license,year
      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          if [[ $(gh pr list --label license,year --json number -q .[].number | wc -l) -gt 0 ]]; then
          gh pr merge --rebase --delete-branch;
          fi
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@0.16.0
        with:
          github_token: ${{ secrets.pat }}
          increment: PATCH
          changelog_increment_filename: body.md
      - name: Release on Github
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
