---
name: CI Generic

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      pat:
        required: true
      token:
        required: true

jobs:
  ci-generic:
    name: ci-generic
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: >-
      ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.pat }}
      - name: Update License year
        uses: FantasticFiasco/action-update-license-year@v2
        if: >-
          ${{ github.ref_name == 'main' }}
        with:
          token: ${{ secrets.token }}
          assignees: jlec
          labels: license,year
      - name: Merge Year Bump PR
        if: >-
          ${{ github.ref_name == 'main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}
        run: |-
          if [[ $(gh pr list --label license,year --json number -q .[].number | wc -l) -gt 0 ]]; then
          gh pr merge --rebase --delete-branch
          else
          git checkout main
          fi
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@0.16.3
        if: >-
          ${{ github.ref_name == 'main' }}
        with:
          github_token: ${{ secrets.pat }}
          increment: PATCH
          changelog_increment_filename: body.md
      - name: Release on Github
        uses: softprops/action-gh-release@v1
        if: >-
          ${{ github.ref_name == 'main' }}
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
      - name: Print Version
        if: >-
          ${{ github.ref_name == 'main' }}
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
