---
name: CI Generic

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      pat:
        required: false

jobs:
  ci-generic:
    name: ci-generic
    runs-on: ubuntu-latest
    # trunk-ignore(checkov/CKV2_GHA_1)
    permissions:
      pull-requests: write
      contents: write
    if: >-
      ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.GHA_CLIENT_ID }}
          private-key: ${{ secrets.GHA_APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
