---
name: Dependabot PR

# yamllint disable-line rule:truthy
on:
  workflow_call: {}

jobs:
  dependabot:
    name: dependabot
    runs-on: ubuntu-latest
    # trunk-ignore(checkov/CKV2_GHA_1)
    permissions:
      pull-requests: write
      contents: write
    if: >-
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event_name == 'pull_request'
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.GHA_CLIENT_ID }}
          private-key: ${{ secrets.GHA_APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Merge Dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          target: minor,patch
