---
name: TF Provider Releaser

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      gpg_release_key:
        required: true

jobs:
  goreleaser:
    name: goreleaser
    runs-on: ubuntu-latest
    # trunk-ignore(checkov/CKV2_GHA_1)
    permissions:
      contents: write
      statuses: write
    env:
      GOPRIVATE: github.com/go-jlec
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.GHA_CLIENT_ID }}
          private-key: ${{ secrets.GHA_APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Cache Go modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup GO
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          cache: true
          go-version-file: "go.mod"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - name: Setup OpenTOFU
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
      - name: Setup tfplugindocs
        run: go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest

      - name: Configure git credentials for private repositories
        run: >-
          git config --global
          url.'https://jlec:${{ steps.app-token.outputs.token }}@github.com/'.insteadOf https://github.com/
      - name: Configure git credentials for private repositories (alternative)
        run: >-
          git config --global
          url.'https://jlec:${{ steps.app-token.outputs.token }}@github.com/'.insteadOf 'https://github.com/'
      - name: Configure git to use https instead of git protocol
        run: "git config --global url.'https://'.insteadOf git://"
      - name: Configure git user name
        run: "git config --global user.name jlec"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.gpg_release_key }}
      - name: Release GO code
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      - name: Cleanup action status
        uses: ouzi-dev/commit-status-updater@26588d166ff273fc4c0664517359948f7cdc9bf1 # v2.0.2
        with:
          status: "success"
          token: ${{ steps.app-token.outputs.token }}
          name: "GithubActions - ${GITHUB_WORKFLOW}"
          ignoreForks: true
