---
name: Linting

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  workflow_call:
    secrets:
      ansible-deploy-keys:
        required: false
      github-token:
        required: true
    inputs:
      ansible-support:
        default: false
        required: false
        type: boolean

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    env:
      PY_RUNNER: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: "git config --global url.'https://jlec:${{ secrets.github-token }}@github.com/'.insteadOf git@github.com:"
      # yamllint disable-line rule:line-length
      - run: "git config --global url.'https://jlec:${{ secrets.github-token }}@github.com/'.insteadOf 'https://github.com/'"
      - run: "git config --global url.'https://'.insteadOf git://"
      - run: "git config --global user.name jlec"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # Set up to your needs
          # cache:
          python-version: ">=3.12"
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        if: ${{ inputs.ansible-support }}
        with:
          ssh-private-key: >-
            ${{ secrets.ansible-deploy-keys }}
      - name: Setup GIT user
        uses: fregante/setup-git-user@v2.0.1
      - name: Install GO
        uses: actions/setup-go@v5
        with:
          # Enable of go.sum is present
          # cache: true
          go-version: ">=1.21.0"
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: latest
      - name: Install shfmt
        uses: mfinelli/setup-shfmt@v3
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install ansible deps in deployment
        run: "if [[ -d deployment ]]; then cd deployment && task ansible-init; fi"
      - name: Install ansible deps in packer
        run: "if [[ -d packer ]]; then cd packer && task ansible-init; fi"
      - name: Install ansible deps
        run: "task ansible-init"
      - name: Run pre-commit against all files
        uses: pre-commit/action@v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          # yamllint disable-line rule:line-length
          SKIP: detect-aws-credentials,protect-first-parent,terraform_docs,terraform_providers_lock,terraform_tflint,terraform_tfsec,terraform_checkov,terrascan,helm-docs-built,go-vet,go-unit-tests,go-static-check,tfupdate,terraform_validate,terragrunt_validate
      # RUN GITLEAKS
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        if: ${{ github.repository_owner == 'jlec' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
