---
name: Dependabot PR

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  dependabot:
    name: dependabot
    runs-on: ubuntu-latest
    # trunk-ignore(checkov/CKV2_GHA_1)
    permissions:
      pull-requests: write
      contents: write
    # trunk-ignore(actionlint/if-cond)
    if: >-
      ${{ github.actor == 'dependabot[bot]' }} &&
      ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.github-token }}
      - name: Merge Dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.github-token }}
          target: minor,patch
